site_name: Miner Curiosity
site_description: A blog for my many distractions
site_author: Matt Miner

extra_css:
  - extra_css/main.css
extra_javascript:
  - extra_js/main.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - extra_js/tablesort.js

theme:
  name: material
  primary: indigo
  accent: indigo
  favicon: assets/images/favicon.ico
  icon:
    logo: material/book
  custom_dir: custom_theme

markdown_extensions:
  - tables
  - meta
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.smartsymbols
# plugins:
#   - tags
# shortcuts:
#   search: 83
