site_name: Miner Curiosity
site_description: A blog for my many distractions
site_author: Matt Miner

nav:
  - Home: index.md

extra_css:
  - extra_css/main.css
extra_javascript:
  - extra_js/main.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - extra_js/tablesort.js

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  primary: indigo
  accent: indigo
  favicon: assets/images/favicon.ico
  icon:
    logo: material/book
  custom_dir: custom_theme
  features:
    - navigation.tabs

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/minercuriosity/

copyright: Copyright &copy Minercuriosity 2021 Matt Miner. All opinions expressed are my own

markdown_extensions:
  - footnotes
  - tables
  - meta
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.smartsymbols

plugins:
  - tags:
      tags_file: tags.md
  - search
