# Project Information
site_name: Miner Curiosity
site_description: A blog for my many distractions
site_author: Matt Miner

# Repository Information
# repo_name: minerupset/mkdocs-blog
# repo_url: https://github.com/minerupset/mkdocs-blog
# edit_uri: ""

nav:
  - Home: index.md
  - By Tag: tags.md
  - About: about.md
  - Legal: legal.md

extra_css:
  - extra_css/main.css
extra_javascript:
  - extra_js/main.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - extra_js/tablesort.js

theme:
  name: material
  # Colors
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=color#primary-color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: assets/images/favicon.ico
  icon:
    logo: material/book
  custom_dir: custom_theme
  features:
    - navigation.tabs
    - navigation.instant?
    - navigation.indexes
    - content.code.annotate

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/minercuriosity/
    - icon: fontawesome/brands/github
      link: https://github.com/minerupset
  analytics:
    provider: google
    property: G-KN729B66EF
  extra:
  consent:
    title: Cookie consent
    description: We use cookies to recognize your repeated visits and preferences. We do not sell your data, because that's rude.

copyright: Copyright &copy Minercuriosity 2021 Matt Miner. Opinions expressed are my own and do not reflect any employer

# Improvements to the markdown processor
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=smartsymbols#highlight
markdown_extensions:
  - footnotes
  - tables
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.smartsymbols

plugins:
  - tags:
      tags_file: tags.md
  - search
