site_name: Miner Curiosity

nav:
  - C#:
      - Hello World: csharp-hello-world.md
  - Python:
      - Hello World: python-hello-world.md
  - Node.JS:
      - Hello World: js-hello-world.md
  - React.JS:
      - Hello World: js-hello-react.md
  - Other JS:
      - Hello World: js-hello-jquery.md
  - Other Tools:
      - VS Code Tools: vs-code-tools.md
      - Git / GitHub: git-github-learnings.md
      - Basic HTML & CSS: html-and-css.md
      - Terminal / Shell Scripting: os-scripting.md
      - RPi For Development: rpi-for-development.md
extra_css:
  - extra_css/extra.css
extra_javascript:
  - extra_js/extra.js
theme:
  name: material
  primary: indigo
  accent: indigo
  favicon: "docs/img/favicon.ico"
  logo:
    icon: build
  custom_dir: custom_theme

shortcuts:
  search: 83
