site_name: Miner Curiosity

nav:
  - C#:
      - Hello World: csharp-hello-world.md
  - Python:
      - Hello World: python-hello-world.md
  - JavaScript:
      - Hello World: js-hello-world.md
  - Other Tools:
      - VS Code Tools: vs-code-tools.md
      - Git / GitHub: git-github-learnings.md
      - Basic HTML & CSS: html-and-css.md
      - Terminal / Shell Scripting: os-scripting.md
extra_css:
  - extra_css/extra.css
extra_javascript:
  - extra_js/extra.js
theme:
  name: mkdocs
  site_favicon: favicon.ico
  custom_dir: custom_theme

shortcuts:
  search: 83
