site_name: Miner Curiosity

nav:
  - C#:
      - Hello World: csharp/hello-world.md
  - Python:
      - Hello World: python/hello-world.md
      - Working With Files: python/working-with-files.md
  - Node.JS:
      - Hello World: js/hello-world.md
      - Non-blocking and Concurrency: js/non-blocking-vs-concurrent.md
      - Intro to Webscraping: js/intro-to-webscraping.md
  - React.JS:
      - Hello React: js/hello-react.md
  - Vanilla JS:
      - Basic Web Interactivity: js/basic-web-js.md
      - Callbacks, Promises, & Async: js/callbacks-promises-async.md
  - Git / GitHub:
      - Git Introduction: git/intro.md
      - Git Reminders: git/reminders.md
  - Databases:
      - Basic DB Information: databases/intro-to-dbs.md
  - Other Tools:
      - VS Code Tools: other/vs-code-tools.md
      - Basic HTML: other/html.md
      - Basic CSS: other/css.md
      - Terminal / Shell Scripting: other/os-scripting.md
      - RPi For Development: other/rpi-for-development.md

extra_css:
  - extra_css/extra.css
extra_javascript:
  - extra_js/extra.js

theme:
  name: material
  primary: indigo
  accent: indigo
  favicon: "assets/images/favicon.ico"
  icon:
    logo: material/book
  custom_dir: custom_theme
  # Adds top level headers as categories, left side headers as pages, toc on right
  # feature:
  #   tabs: true

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.smartsymbols

shortcuts:
  search: 83
